package.json
Since we moved to the scoped package name, we can't directly execute it with `npx`. This PR adds an alias to have `eslint-config-inspector` registered as the cli command as well
=> feat: support global install with cli name

components/RuleItem.vue
Hi,
Thanks to antfu for this project, great to see it's now an officially endorsed effort.
A very small change here: I believe `Documentations` isn't general vernacular.
Before:
After:
=> chore: update wording

app.vue, components/NavBar.vue, components/RuleItem.vue, pages/configs.vue, pages/rules.vue, styles/global.css, uno.config.ts
Resolves #13, aligning the color palette and fonts.
About the icons for rules, I took a middle ground to have monochrome icons on the listing (to make it less visually prominent and put the emojis in the tooltip to make the "connection" with the ecosystem's practice).
=> feat: align better with ESLint's design system

app/components/ConfigItem.vue, app/server/api/payload.json.ts, package.json, pnpm-lock.yaml, src/cli.ts, src/configs.ts, src/server.ts, src/ws.ts, types.ts
fix #25
- Configs now resolved with `find-up`, aligning with ESLint
- When no arguments are provided, the cwd will be changed to the directory for the found config file
- When config path is provided, the cwd will keep at the command cwd
- When root path is provided but not the config, the config will be searched from the root path
=> feat: improve how configures are resolved

app/styles/global.css
| before | after |
|  ----  | ----  |
| ![IMG_0411](https://github.com/eslint/config-inspector/assets/38493346/9192a656-d311-4044-9ea3-dc41c204a99d)  | ![IMG_0410](https://github.com/eslint/config-inspector/assets/38493346/407bec3c-37f3-4408-b4e6-9bfbbb5cf6c7) |
=> fix: hide detail marker on safari

package.json, pnpm-lock.yaml, src/cli.ts, src/server.ts
In current, the project use `connect` and `sirv` to create server and serving static assets. The last publish of `connect` is 5 years ago. It's very old and inactive.
The [unjs/h3](https://h3.unjs.io/) is a good alternative. And it already includes `serveStatic` utility.
=> refactor: use `h3` to create server

shared/configs.ts
Fixes #49
In flat config, patterns without a slash do not match at any level.
https://github.com/eslint/rewrite/blob/a136341eafbb092544d7aef19cc22f57104a572a/packages/config-array/src/config-array.js#L56-L63
=> fix: use minimatch without `matchBase:true`

src/cli.ts
If the hostname is localhost / 127.0.0.1, the log print host name and opened hostname are different:
So this PR alignment the print hostname with the opened hostname.
The opened hostname source:
https://github.com/eslint/config-inspector/blob/e7b655226c4d25bf623919b317bdc45a90eda6c4/src/cli.ts#L102-L106
=> fix: alignment hostname

src/configs.ts
The default config in ESLint is always prepended to the config before it uses the config, making it so that `**/*.js`, `**/*.mjs`, `**/*.cjs` are always matching file patterns: https://github.com/eslint/eslint/blob/21d3766c3f4efd981d3cc294c2c82c8014815e6e/lib/config/default-config.js#L66-L69
This PR copies those two configs and prepends them here as well, with some added names for them to make sense.
This is somewhat of a blunt fix. UI-wise it can be handled better and ideally one or more of `defaultConfig`, `FlatConfigArray` and `calculateConfigArray` would be exposed by ESLint so that this inspector can make use of the very same logic rather than attempt to reimplement it.
If additionally `defaultConfig` were to eg. add names, then this inspector could opt to eg. hide all `eslint/` …
=> fix: match default file patterns as well

package.json, pnpm-lock.yaml, src/configs.ts
Fixes #59
Following the discussions in https://github.com/eslint/eslint/issues/18619 I went ahead and made a proof of concept extraction of the small core logic that ESLint uses to iterate over the files of a directory, using a `ConfigArray` as guidance.
I published it at [`configArrayFindFiles()`](https://github.com/voxpelli/config-array-find-files) and here is a PR that makes use if it.
It uses a fake schema to load the configs into `ConfigArray` as there is no published official one that can be used yet (https://github.com/eslint/eslint/issues/18619#issuecomment-2183187174)
Hopefully `@eslint/config-array` itself will get a `configArrayFindFiles()` equivalent eventually, but we need to start somewhere.
The way that `configArrayFindFiles()` is constructed it could also simplify ESLint's …
=> fix: use `@eslint/config-array` to resolve paths

app/components/NavBar.vue, app/composables/state.ts, app/pages/rules.vue
When users are not in page rules and clicking the toggleRuleView button, nothing woud happen.
It's strange.
So this PR moves the `toggleRuleView` button to page rules.
This is how it looks like now:
---
Besides, a little style change made to rules filter.
Before:
After:
=> fix: move toggleRuleView to page rules

app/components/FileGroupItem.vue
Was confused by this until realizing the caption was referring to configs instead.
(It would incidentally be nice to have applicable rules listed if possible, but that's another issue.)
=> fix: label of "Rules" -> "Configs" on file group

app/composables/strings.ts
While 11th, 12th, 13th uses `th` all other numbers that end with 1, 2 or 3 use same suffix as the base 1, 2 and 3
For reference, see eg: https://www.mathsisfun.com/numbers/cardinal-ordinal-chart.html
Fixes #74
=> fix: `nth` formatting for values above 20

app/components/ConfigItem.vue
Fixes #80
Alternative solution would be:
```js
Object.keys(config).length > 2
```
But I think its clearer when the two indexes are checked explicitly (`'index'` being one added by config inspector)
=> fix: improved check of whether ignore is global

src/cli.ts, src/configs.ts, src/constants.ts, src/errors.ts, src/ws.ts
Fixes #82
When encountering no flat config it now checks for a legacy config and if found it will output this error message now:
And if no legacy config file is found either, then it will tell the user what files it looked for and in what folder:
=> feat: improved errors when config can not be found

README.md
Related to #87 
I didn't know there was a `--base` CLI option (I should have tried `--help`, but I assumed there were no options from looking at the readme), this just reformats the `--help` output as a markdown table.
=> docs: add CLI options to readme

app/components/RuleItem.vue, app/composables/payload.ts, shared/types.ts
This PR labels non-existent rules as `INVALID`.
A rule would be removed after deprecated.
If users didn't remove it ASAP, prop `rule` of component **RuleItem** would be undefined and cause render errors.
=> feat: label non-existent rule as invalid

app/components/RuleItem.vue, app/components/RuleLevelIcon.vue, app/components/RuleStateItem.vue, app/components/Shiki.ts, app/composables/options.ts, app/composables/payload.ts, app/composables/strings.ts, app/styles/global.css, package.json, pnpm-lock.yaml, pnpm-workspace.yaml, shared/types.ts
Implements https://github.com/eslint/config-inspector/discussions/108
Utilises the newly available `meta.defaultOptions` (available [since eslint v9.15.0](https://github.com/eslint/eslint/pull/17656)) to introduce three UI changes:
1. Adds a pair of buttons to the `RuleStateItem` component for toggling between the configured options and the default options for the rule:
2. When viewing the configured options, any values that match the default are shown in italics and 75% opacity:
3. If any configured options match the defaults, the "has options" indicator dot at the top right corner changes color to blue:
=> feat: present `meta.defaultOptions` in the config inspector

app/components/ConfigItem.vue, app/components/FileGroupItem.vue, app/components/OptionSelectGroup.vue
`defineModel` is a compiler macro and no longer needs to be imported.
=> chore: remove unused import

app/components/RuleDeprecatedInfo.vue, app/components/RuleItem.vue
Add a dropdown to display deprecated information from plugins.
Dark mode:
Light mode:
I'm not sure if the style is ok. Some suggestions are welcome. :)
=> feat: display rule deprecated info
